name: Vigil Heartbeat Trigger
on:
  schedule:
    - cron: '*/5 * * * *' # Runs every 5 minutes
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Vigil Heartbeat
        run: |
          curl -X GET "https://vercel.com/abdelrahman-ashrafs-projects-29915a44/vigil/4kH5rBTSwJzx4BCRxEnUr2Tu8DT5/api/cron/heartbeat" \
          -H "x-api-key: ${{ secrets.CRON_SECRET }}"